# Generated by Django 2.0.2 on 2019-03-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
